In [1]:
from g474 import *

COM15: STMicroelectronics STLink Virtual COM Port (COM15) [USB VID:PID=0483:374B SER=066CFF3530454D3043032340 LOCATION=1-1:x.2]

In [2]:
RCC.AHB2ENR

DEC: 35, HEX: 0x00000023

In [3]:
 RCC.AHB2ENR.GPIOCEN = 1

In [4]:
RCC.AHB2ENR

DEC: 39, HEX: 0x00000027

In [5]:
RCC.APB2ENR

DEC: 1, HEX: 0x00000001

In [6]:
RCC.APB2ENR.TIM1EN = 1

In [7]:
RCC.APB2ENR

DEC: 2049, HEX: 0x00000801

In [8]:
GPIOC.MODER

DEC: 4294967295, HEX: 0xFFFFFFFF

In [9]:
GPIOC.MODER = 0XFFFFFFEA

In [10]:
GPIOC.MODER

DEC: 4294967274, HEX: 0xFFFFFFEA

In [11]:
GPIOC.AFRL

DEC: 0, HEX: 0x00000000

In [12]:
GPIOC.AFRL = 0X00000222

In [13]:
GPIOC.AFRL

DEC: 546, HEX: 0x00000222

In [14]:
TIM1.CCMR1

DEC: 0, HEX: 0x00000000

In [15]:
TIM1.CCMR1 = 0X00006060

In [16]:
TIM1.CCMR1

DEC: 24672, HEX: 0x00006060

In [17]:
TIM1.CCMR2 = 0X00000060

In [18]:
TIM1.CCMR2

DEC: 96, HEX: 0x00000060

In [19]:
TIM1.CCER

DEC: 0, HEX: 0x00000000

In [53]:
TIM1.CCER = 0X00000333

In [21]:
TIM1.CCER

DEC: 51, HEX: 0x00000033

In [22]:
TIM1.BDTR

DEC: 0, HEX: 0x00000000

In [23]:
TIM1.BDTR = 1<<15

In [24]:
TIM1.BDTR = 0X00008000#0x00008064

In [25]:
TIM1.BDTR

DEC: 32768, HEX: 0x00008000

In [26]:
TIM1.PSC

DEC: 0, HEX: 0x00000000

In [27]:
TIM1.PSC = 0

In [28]:
TIM1.PSC

DEC: 0, HEX: 0x00000000

In [29]:
TIM1.ARR

DEC: 65535, HEX: 0x0000FFFF

In [30]:
TIM1.ARR = 99

In [31]:
TIM1.ARR

DEC: 99, HEX: 0x00000063

In [32]:
TIM1.CR1

DEC: 0, HEX: 0x00000000

In [33]:
TIM1.CR1 = 1

In [34]:
TIM1.CR1

DEC: 1, HEX: 0x00000001

In [35]:
TIM1.CCR1

DEC: 0, HEX: 0x00000000

In [36]:
TIM1.CCR1 = 50

In [37]:
TIM1.CCR1

DEC: 50, HEX: 0x00000032

In [38]:
TIM1.CCR1 = 100

In [39]:
TIM1.CCR1 = 10

In [40]:
TIM1.CCR2 = 50

In [41]:
TIM1.CR2

DEC: 0, HEX: 0x00000000

In [42]:
TIM1.CCR2 = 50

In [43]:
TIM1.CCR2

DEC: 50, HEX: 0x00000032

In [44]:
TIM1.CCR1 = 0

In [50]:
TIM1.CCR2 = 100

In [52]:
TIM1.CCR3 = 100

In [51]:
TIM1.CCR2 = 0

In [55]:
TIM1.CCR3 = 0

In [54]:
TIM1.CCR3

DEC: 100, HEX: 0x00000064